wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.17
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745702236.624824
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.10.17
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
input_artifact:
  desc: null
  value: sample.csv
output_artifact:
  desc: null
  value: clean_sample
output_type:
  desc: null
  value: clean_sample
output_description:
  desc: null
  value: Cleaned dataset with price filtering
min_price:
  desc: null
  value: 10.0
max_price:
  desc: null
  value: 500.0
